import { COLOR_TOKENS, MOTION_TOKENS, SCALE_TOKENS } from "./tokens";

export function cssVarName(name: string): string {
  return `--qm-${name.replaceAll(".", "-")}`;
}

/** CSS custom properties: :root is day, data-theme on <html> selects night or redShift (spec 6.5). */
export function buildCss(): string {
  const lines = ["/* Generated by packages/tokens/scripts/gen-css.ts. Do not edit. */", ":root {"];
  for (const [name, value] of Object.entries(SCALE_TOKENS))
    lines.push(`  ${cssVarName(name)}: ${value};`);
  for (const [name, values] of Object.entries(COLOR_TOKENS))
    lines.push(`  ${cssVarName(name)}: ${values.day};`);
  lines.push("}");
  for (const mode of ["night", "redShift"] as const) {
    lines.push(`:root[data-theme="${mode}"] {`);
    for (const [name, values] of Object.entries(COLOR_TOKENS))
      lines.push(`  ${cssVarName(name)}: ${values[mode]};`);
    lines.push("}");
  }
  lines.push("@media (prefers-reduced-motion: reduce) {", "  :root {");
  for (const name of MOTION_TOKENS) lines.push(`    ${cssVarName(name)}: 0ms;`);
  lines.push("  }", "}");
  return `${lines.join("\n")}\n`;
}
